# Generated by Django 4.1.5 on 2023-01-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='penguin-svgrepo-com.svg', null=True, upload_to=''),
        ),
    ]
